services:
  api:
    container_name: entain-api__app__production
    image: node:22.12.0-alpine
    restart: unless-stopped
    working_dir: /usr/app/
    ports:
      - '3000:3000'
    volumes:
      - ./api:/usr/app/
    networks:
      - entain-shared
    command: >
      sh -c 'corepack enable
      && corepack prepare pnpm@9.15.2 --activate
      && pnpm i
      && pnpm build
      && pnpm start:prod'
    env_file:
      - ./api/.env
  web:
    container_name: entain-web__app__production
    image: node:22.12.0-alpine
    restart: unless-stopped
    working_dir: /usr/app/
    ports:
      - '80:3000'
    volumes:
      - ./web:/usr/app/
    networks:
      - entain-shared
    command: >
      sh -c 'corepack enable
      && corepack prepare pnpm@9.15.2 --activate
      && pnpm i
      && pnpm build
      && pnpm start'
    depends_on:
      api:
        condition: service_started
    env_file:
      - ./web/.env
networks:
  entain-shared:
    driver: bridge
