services:
  web:
    container_name: entain-web__app__development
    image: node:22.12.0-alpine
    env_file:
      - .env
    restart: unless-stopped
    working_dir: /usr/app/
    volumes:
      - .:/usr/app/
    ports:
      - '${WEB_EXPOSED_PORT:-3003}:3000'
    command: >
      sh -c 'corepack enable
      && corepack prepare pnpm@9.15.2 --activate
      && pnpm i
      && pnpm dev'
